/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
    automateAutoScoreToggle?: boolean;
    api?: {
        startgg?: {
            key?: string;
            [k: string]: unknown;
        };
        [k: string]: unknown;
    };
    hudTemplatePath?: string;
    slpDumpPath?: {
        inBundle?: boolean;
        path?: string;
        [k: string]: unknown;
    };
    obs?: {
        scenes?: {
            Handwarmer?: {
                autoSwitch?: boolean;
                delay?: number;
                [k: string]: unknown;
            };
            Tournament?: {
                autoSwitch?: boolean;
                delay?: number;
                [k: string]: unknown;
            };
            'Game End'?: {
                autoSwitch?: boolean;
                delay?: number;
                [k: string]: unknown;
            };
            'Set End'?: {
                autoSwitch?: boolean;
                delay?: number;
                [k: string]: unknown;
            };
            Wait?: {
                autoSwitch?: boolean;
                delay?: number;
                [k: string]: unknown;
            };
            [k: string]: unknown;
        };
        [k: string]: unknown;
    };
    extraStats?: unknown[];
    [k: string]: unknown;
}
