/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Players = {
    id?: number;
    slippiIndex?: number;
    teamId?: number;
    name?: string;
    pronouns?: string;
    country?: string;
    countryId?: number;
    sponsor?: string;
    initialSeeding?: number;
    [k: string]: unknown;
}[];
