/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Slippi {
    connection: {
        connected?: boolean;
        type?: string;
        address?: string;
        port?: number;
        [k: string]: unknown;
    };
    gameInfo: {
        started?: boolean;
        finished?: boolean;
        isTeams?: boolean;
        activeTeams?: number[];
        elapsedFrames?: number;
        timer?: {
            minutes?: number;
            seconds?: number;
            milliseconds?: number;
            formatted?: string;
            rawFrames?: number;
            framerate?: number;
            [k: string]: unknown;
        };
        stage?: {
            id?: number;
            fullName?: string;
            shortName?: string;
            [k: string]: unknown;
        };
        [k: string]: unknown;
    };
    playerInfo: {
        id?: number;
        index?: number;
        port?: number;
        teamId?: number;
        character?: {
            id?: number;
            fullName?: string;
            shortName?: string;
            costumeId?: number;
            costumeName?: string;
            [k: string]: unknown;
        };
        stockCountStart?: number;
        stockCountNow?: number;
        tag?: string;
        display?: string;
        connect?: string;
        damage?: number;
        controller?: {
            mainStickX?: number;
            mainStickY?: number;
            cStickX?: number;
            cStickY?: number;
            rawButtons?: number;
            leftTrigger?: number;
            rightTrigger?: number;
            pressedButtons?: {
                A?: boolean;
                B?: boolean;
                X?: boolean;
                Y?: boolean;
                Z?: boolean;
                L?: boolean;
                R?: boolean;
                START?: boolean;
                D_UP?: boolean;
                D_RIGHT?: boolean;
                D_DOWN?: boolean;
                D_LEFT?: boolean;
                [k: string]: unknown;
            };
            [k: string]: unknown;
        };
        misc?: {
            'isFollower:'?: boolean;
            actionStateId?: number;
            positionX?: number;
            positionY?: number;
            facingDirection?: number;
            shieldSize?: number;
            lastAttackLanded?: number;
            currentComboCount?: number;
            lastHitBy?: number;
            actionStateCounter?: number;
            miscActionState?: number;
            'isAirborne:'?: boolean;
            lastGroundId?: number;
            jumpsRemaining?: number;
            lCancelStatus?: number;
            hurtboxCollisionState?: number;
            selfInducedSpeeds?: {
                airX?: number;
                y?: number;
                attackX?: number;
                attackY?: number;
                groundX?: number;
                [k: string]: unknown;
            };
            [k: string]: unknown;
        };
        [k: string]: unknown;
    }[];
    [k: string]: unknown;
}
