/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Startgg {
    tournamentSyncEnabled?: boolean;
    tournamentSlug?: string;
    availableQueues?: {
        streamName?: string;
        activeSet?: {
            id?: number;
            round?: number;
            lPlacement?: number;
            startedAt?: number;
            [k: string]: unknown;
        };
        [k: string]: unknown;
    }[];
    availableEvents?: {
        id?: number;
        name?: string;
        type?: number;
        [k: string]: unknown;
    }[];
    selectedQueue?: number;
    selectedEvent?: number;
    boAutomationEnabled?: boolean;
    boIntegerThreshold?: number;
    [k: string]: unknown;
}
